version: '3.0'
services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx:${USER}
    volumes:
      - wordpress-data:/var/www/html
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - NGINX_CONF=${NGINX_CONF}
        - COUNTRY_NAME=${COUNTRY_NAME}
        - STATE_NAME=${STATE_NAME}
        - LOCALITY_NAME=${LOCALITY_NAME}
        - ORGANIZATION_NAME=${ORGANIZATION_NAME}
        - COMMON_NAME=${COMMON_NAME}
    ports:
      - 443:443
    networks:
      - docker-network
    restart: unless-stopped
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress:${USER}
    volumes:
      - wordpress-data:/var/www/html
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - MARIADB_DB_NAME=${MARIADB_DB_NAME}
        - MARIADB_USER_NAME=${USER}
        - MARIADB_USER_PASSWD=${MARIADB_USER_PASSWD}
    networks:
      - docker-network
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    image: mariadb:${USER}
    volumes:
      - type: bind
        source: /home/${USER}/data # edit path /home/${USER}/data
        target: /var/lib/mysql
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MARIADB_ROOT_PASSWD=${MARIADB_ROOT_PASSWD}
        - MARIADB_USER_NAME=${USER}
        - MARIADB_USER_PASSWD=${MARIADB_USER_PASSWD}
        - MARIADB_DB_NAME=${MARIADB_DB_NAME}
    networks:
      - docker-network
    restart: unless-stopped

# volumes:
#   wordpress-data:
volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: ${VOLPATH}/mariadb
      o: bind
      type: volume
    name: mariadb-volume
  wordpress-volume:
    driver: local
    driver_opts:
      device: ${VOLPATH}/wordpress
      o: bind
      type: volume
    name: wordpress-volume
networks: 
  docker-network:
